### ISSUE TITLE
Should we also add a section for cool little projects ?

### ISSUE THREAD

**Issue by mransan** [reasonml-community/index#8]
Things like [this](https://github.com/jaredly/rsnpaint) for example are awesome little examples of using OCaml/Reason/Bucklescript!

**Comment by glennsl** [comment]
I'm not sure. It's certainly something I'd like to see somewhere, but it's really out of scope here since it's not something you'd "use". And it's not obvious what should and should not be included. But then maybe the scope is wrong. Maybe it would actually be more useful to have this all in one place...

**Comment by mransan** [comment]
We could have BuckleTypes/examples maybe ? @chenglou  what do you think ?

**Comment by glennsl** [comment]
There's [bs-examples](https://github.com/BuckleTypes/bs-examples) already, which might just as well have a list of external repos in its readme. I'm also planning on starting a bucklescript cookbook, "inspired by" [rust-cookbook](https://brson.github.io/rust-cookbook)

**Comment by mransan** [comment]
Yes that would pretty good!

**Comment by glennsl** [comment]
There's now a section for examples on the frontpage of the BuckleScript homepage (https://bucklescript.github.io/), as well as the Reason homepage, which additionally has a separate page (https://reasonml.github.io/community/examples).

And the cookbook is here: https://github.com/glennsl/bucklescript-cookbook

I think that should cover it, so I'll close this :)
